# Generated by Django 4.1.3 on 2022-12-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, max_length=150, null=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("published", models.BooleanField(default=True)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "App_Tutorials",
            },
        ),
    ]
